[package]
name = "sailify"
version = "0.1.0"
authors = ["Richard Liebscher <r1tschy@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librespot = "^0.1.3"
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1"
log = "0.4"
sha-1 = "0.8"
url = "1.7"
hex = "0.3"
tokio-signal = "0.2"
env_logger =  {version = "0.6", default-features = false, features = ["termcolor","humantime","atty"]}
